export const sampleRegistry = {
  agents: [
    {
      id: 'sample-claim-verification',
      name: 'Claim Verification Agent',
      version: '1.0.0',
      author: 'A2A Registry',
      description: 'Verifies claims against published sources and produces a concise evidence summary for downstream workflows.',
      skills: [
        { name: 'Claim Check', tags: ['verification', 'research', 'analysis'] },
        { name: 'Evidence Trace', tags: ['citations', 'summaries'] },
      ],
      conformance: true,
      capabilities: { streaming: true, pushNotifications: false },
      uptime_percentage: 99.3,
      avg_response_time_ms: 842,
      last_health_check: '2026-03-08T09:30:00Z',
      status_notes: ['Healthy endpoint checks in the last 24 hours.'],
      protocolVersion: '0.3.0',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'MIT',
      maintainer_notes: [
        'Best used as a demo of the high-trust detail layout.',
        'This sample intentionally includes clean health signals, valid docs, and a short markdown note.',
      ].join('\n\n'),
      created_at: '2026-03-07T10:15:00Z',
    },
    {
      id: 'sample-market-research',
      name: 'Market Research Scout',
      version: '0.9.2',
      author: 'A2A Registry',
      description: 'Collects category signals, competitor changes, pricing patterns, and launches into a daily strategic brief.',
      skills: [
        { name: 'Market Scan', tags: ['research', 'pricing', 'discovery'] },
        { name: 'Trend Watch', tags: ['signals', 'analysis', 'alerts'] },
      ],
      conformance: true,
      capabilities: { streaming: false, pushNotifications: true },
      uptime_percentage: 96.1,
      avg_response_time_ms: 1284,
      last_health_check: '2026-03-08T09:25:00Z',
      status_notes: ['Slightly slower response times during peak usage.'],
      protocolVersion: '0.3.0',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'Apache-2.0',
      maintainer_notes: [
        'Useful for testing cards with no streaming badge but stronger tag density.',
        'The response time is intentionally slower so the trust section has more contrast.',
      ].join('\n\n'),
      created_at: '2026-03-06T08:05:00Z',
    },
    {
      id: 'sample-compliance-monitor',
      name: 'Compliance Monitor',
      version: '1.2.4',
      author: 'A2A Registry',
      description: 'Tracks policy and regulatory changes across selected markets and flags the updates that require action.',
      skills: [
        { name: 'Policy Monitor', tags: ['compliance', 'monitoring', 'alerts'] },
        { name: 'Regulatory Brief', tags: ['research', 'summaries', 'workflow'] },
      ],
      conformance: false,
      capabilities: { streaming: true, pushNotifications: true },
      uptime_percentage: 84.8,
      avg_response_time_ms: 2110,
      last_health_check: '2026-03-08T09:20:00Z',
      status_notes: ['Low uptime during the last 7 days.', 'Requires manual validation for high-risk production use.'],
      protocolVersion: '0.2.1',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'MIT',
      maintainer_notes: [
        'This sample exists to show the non-standard path and a more cautionary trust state.',
        '- Lower uptime',
        '- Mixed health notes',
        '- Push + streaming capabilities',
      ].join('\n'),
      created_at: '2026-03-05T14:40:00Z',
    },
    {
      id: 'sample-conversation-router',
      name: 'Conversation Router',
      version: '2.1.0',
      author: 'A2A Registry',
      description: 'Routes incoming user intents to downstream specialized agents and keeps a lightweight audit trail of handoffs.',
      skills: [
        { name: 'Intent Router', tags: ['routing', 'workflow', 'delegation'] },
        { name: 'Audit Trail', tags: ['logging', 'governance'] },
      ],
      conformance: true,
      capabilities: { streaming: true, pushNotifications: true },
      uptime_percentage: 97.7,
      avg_response_time_ms: 694,
      last_health_check: '2026-03-08T09:10:00Z',
      status_notes: ['Healthy endpoint checks in the last 24 hours.'],
      protocolVersion: '0.3.0',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'MIT',
      maintainer_notes: [
        'Good sample for seeing a denser capability set without health concerns.',
        'Also helps validate the desktop modal against a slightly longer name.',
      ].join('\n\n'),
      created_at: '2026-03-04T16:20:00Z',
    },
    {
      id: 'sample-finance-brief',
      name: 'Finance Brief Generator',
      version: '0.8.7',
      author: 'A2A Registry',
      description: 'Converts raw market, earnings, and macro signals into a structured brief for an analyst or portfolio workflow.',
      skills: [
        { name: 'Brief Builder', tags: ['finance', 'summaries', 'reporting'] },
        { name: 'Signal Triage', tags: ['analysis', 'research', 'market'] },
      ],
      conformance: true,
      capabilities: { streaming: false, pushNotifications: false },
      uptime_percentage: 92.4,
      avg_response_time_ms: 1518,
      last_health_check: '2026-03-08T09:00:00Z',
      status_notes: ['Recovering from a brief outage earlier this week.'],
      protocolVersion: '0.3.0',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: null,
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'Apache-2.0',
      maintainer_notes: [
        'No documentation link on purpose, so the disabled action state stays testable locally.',
      ].join('\n\n'),
      created_at: '2026-03-03T12:00:00Z',
    },
    {
      id: 'sample-security-triage',
      name: 'Security Triage Assistant',
      version: '1.5.1',
      author: 'A2A Registry',
      description: 'Groups findings, prioritizes incidents, and drafts remediation queues for internal security and reliability teams.',
      skills: [
        { name: 'Incident Triage', tags: ['security', 'triage', 'alerts'] },
        { name: 'Remediation Queue', tags: ['workflow', 'prioritization'] },
      ],
      conformance: false,
      capabilities: { streaming: true, pushNotifications: false },
      uptime_percentage: 88.9,
      avg_response_time_ms: 1733,
      last_health_check: '2026-03-08T08:55:00Z',
      status_notes: ['Intermittent timeout spikes during larger requests.'],
      protocolVersion: '0.2.4',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'MIT',
      maintainer_notes: [
        'A second non-standard sample so the filters are worth testing locally.',
        'Use this one to validate the warning-heavy detail presentation.',
      ].join('\n\n'),
      created_at: '2026-03-02T11:45:00Z',
    },
  ],
};
