export const sampleRegistry = {
  agents: [
    {
      id: 'sample-claim-verification',
      name: 'Claim Verification Agent',
      version: '1.0.0',
      author: 'A2A Registry',
      description: 'Verifies claims against published sources and produces a concise evidence summary for downstream workflows.',
      skills: [
        { name: 'Claim Check', tags: ['verification', 'research', 'analysis'] },
        { name: 'Evidence Trace', tags: ['citations', 'summaries'] },
      ],
      conformance: true,
      capabilities: { streaming: true, pushNotifications: false },
      uptime_percentage: 99.3,
      avg_response_time_ms: 842,
      last_health_check: '2026-03-08T09:30:00Z',
      status_notes: ['Healthy endpoint checks in the last 24 hours.'],
      protocolVersion: '0.3.0',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'MIT',
    },
    {
      id: 'sample-market-research',
      name: 'Market Research Scout',
      version: '0.9.2',
      author: 'A2A Registry',
      description: 'Collects category signals, competitor changes, and pricing patterns into a daily strategic brief.',
      skills: [
        { name: 'Market Scan', tags: ['research', 'pricing', 'discovery'] },
        { name: 'Trend Watch', tags: ['signals', 'analysis'] },
      ],
      conformance: true,
      capabilities: { streaming: false, pushNotifications: true },
      uptime_percentage: 96.1,
      avg_response_time_ms: 1284,
      last_health_check: '2026-03-08T09:25:00Z',
      status_notes: ['Slightly slower response times during peak usage.'],
      protocolVersion: '0.3.0',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: null,
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'Apache-2.0',
    },
    {
      id: 'sample-compliance-monitor',
      name: 'Compliance Monitor',
      version: '1.2.4',
      author: 'A2A Registry',
      description: 'Tracks policy and regulatory changes across selected markets and flags the updates that require action.',
      skills: [
        { name: 'Policy Monitor', tags: ['compliance', 'monitoring', 'alerts'] },
        { name: 'Regulatory Brief', tags: ['research', 'summaries'] },
      ],
      conformance: false,
      capabilities: { streaming: true, pushNotifications: true },
      uptime_percentage: 84.8,
      avg_response_time_ms: 2110,
      last_health_check: '2026-03-08T09:20:00Z',
      status_notes: ['Low uptime during the last 7 days.'],
      protocolVersion: '0.2.1',
      url: 'https://www.a2aregistry.org',
      wellKnownURI: 'https://www.a2aregistry.org/.well-known/agent-card.json',
      homepage: 'https://www.a2aregistry.org',
      documentationUrl: 'https://github.com/google/A2A',
      provider: { organization: 'A2A Registry', url: 'https://www.a2aregistry.org' },
      license: 'MIT',
    },
  ],
};
